Note song[1024] = { 
	{.tone = D3,  .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = HALF  },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*A************************************/
/*3************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Fs3, .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = E3,  .beat = TRIP   },
	{.tone = C4,  .beat = TRIP   },
	{.tone = E4,  .beat = TRIP   },
	{.tone = PASS},
	{.tone = F4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D4,  .beat = EIGHTH},
	{.tone = E4,  .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A3,  .beat = EIGHTH},
	{.tone = B3,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*7************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Fs3, .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = E3,  .beat = TRIP},
	{.tone = C4,  .beat = TRIP},
	{.tone = E4,  .beat = TRIP},
	{.tone = PASS},
	{.tone = F4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D4,  .beat = EIGHTH},
	{.tone = E4,  .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A3,  .beat = EIGHTH},
	{.tone = B3,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*B************************************/
/*11***********************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = HALF  },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*15**********************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Gs3, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = As3, .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*************************************/
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*19**********************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = HALF  },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*23**********************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Gs3, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = As3, .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*************************************/
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*C***********************************/
/*27**********************************/
	{.tone = Gs2, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Ds3, .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = Gs3, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
	{.tone = G2,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = Gs2, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Ds3, .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = Gs3, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
	{.tone = G2,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*31**********************************/
	{.tone = Gs2, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Ds3, .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = Gs3, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = Gs3, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G2,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = D3,  .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = HALF  },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*A***********************************/
/*35**********************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Fs3, .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = E3,  .beat = TRIP   },
	{.tone = C4,  .beat = TRIP   },
	{.tone = E4,  .beat = TRIP   },
	{.tone = PASS},
	{.tone = F4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D4,  .beat = EIGHTH},
	{.tone = E4,  .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A3,  .beat = EIGHTH},
	{.tone = B3,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*39***********************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Fs3, .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = E3,  .beat = TRIP},
	{.tone = C4,  .beat = TRIP},
	{.tone = E4,  .beat = TRIP},
	{.tone = PASS},
	{.tone = F4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D4,  .beat = EIGHTH},
	{.tone = E4,  .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A3,  .beat = EIGHTH},
	{.tone = B3,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*D***********************************/
/*43**********************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Fs3, .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = B3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*47**********************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Fs3, .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = G3,  .beat = TRIP   },
	{.tone = A3,  .beat = TRIP   },
	{.tone = B3,  .beat = TRIP   },
	{.tone = PASS},
/*************************************/
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*51**********************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Fs3, .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = B3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*55**********************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Fs3, .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = G3,  .beat = TRIP   },
	{.tone = A3,  .beat = TRIP   },
	{.tone = B3,  .beat = TRIP   },
	{.tone = PASS},
/*************************************/
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*C***********************************/
/*59**********************************/
	{.tone = Gs2, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Ds3, .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = Gs3, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
	{.tone = G2,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = Gs2, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Ds3, .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = Gs3, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
	{.tone = G2,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*63**********************************/
	{.tone = Gs2, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Ds3, .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = Gs3, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
	{.tone = G2,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = D3,  .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = R,   .beat = HALF  },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*D***********************************/
/*67**********************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Fs3, .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = D3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = B3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*71**********************************/
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = Fs3, .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = C4,  .beat = EIGHTH},
	{.tone = F3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/*************************************/
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = G3,  .beat = TRIP   },
	{.tone = A3,  .beat = TRIP   },
	{.tone = B3,  .beat = TRIP   },
	{.tone = PASS},
/*************************************/
	{.tone = C4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	
	{.tone = END}
};
