Note song[1024] = { 
	{.tone = D3,  .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = WHOLE  },
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
/*A************************************/
/*3************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = E3,  .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Fs3, .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = E3,  .beat = TRIP   },
	{.tone = C4,  .beat = TRIP   },
	{.tone = E4,  .beat = TRIP   },
	{.tone = F4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = D4,  .beat = QUARTER},
	{.tone = E4,  .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = A3,  .beat = QUARTER},
	{.tone = B3,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R    .beat = HALF   },
/*7************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = E3,  .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Fs3, .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = E3,  .beat = TRIP},
	{.tone = C4,  .beat = TRIP},
	{.tone = E4,  .beat = TRIP},
	{.tone = F4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = D4,  .beat = QUARTER},
	{.tone = E4,  .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = A3,  .beat = QUARTER},
	{.tone = B3,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R    .beat = HALF   },
/*B************************************/
/*11***********************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER}
	{.tone = R    .beat = HALF   },
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = E3,  .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = G3,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = WHOLE  },
	{.tone = R,   .beat = HALF   },
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*15**********************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Gs3, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = As3, .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
/*************************************/
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*19**********************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER}
	{.tone = R    .beat = HALF   },
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = E3,  .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = G3,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = WHOLE  },
	{.tone = R,   .beat = HALF   },
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*23**********************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Gs3, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = As3, .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
/*************************************/
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*C***********************************/
/*27**********************************/
	{.tone = Gs2, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Ds3, .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = Gs3, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G2,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = Gs2, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Ds3, .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = Gs3, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G2,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*31**********************************/
	{.tone = Gs2, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Ds3, .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = Gs3, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G2,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = D3,  .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = WHOLE  },
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
/*A***********************************/
/*35**********************************/,
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = E3,  .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Fs3, .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = E3,  .beat = TRIP   },
	{.tone = C4,  .beat = TRIP   },
	{.tone = E4,  .beat = TRIP   },
	{.tone = F4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = D4,  .beat = QUARTER},
	{.tone = E4,  .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = A3,  .beat = QUARTER},
	{.tone = B3,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R    .beat = HALF   },
/*39***********************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = E3,  .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Fs3, .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = E3,  .beat = TRIP},
	{.tone = C4,  .beat = TRIP},
	{.tone = E4,  .beat = TRIP},
	{.tone = F4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = D4,  .beat = QUARTER},
	{.tone = E4,  .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = A3,  .beat = QUARTER},
	{.tone = B3,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R    .beat = HALF   },
/*D***********************************/
/*43**********************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Fs3, .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = B3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*47**********************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Fs3, .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = G3,  .beat = TRIP   },
	{.tone = A3   .beat = TRIP   },
	{.tone = B3,  .beat = TRIP   },
/*************************************/
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
/*51**********************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Fs3, .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = B3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*55**********************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Fs3, .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = G3,  .beat = TRIP   },
	{.tone = A3   .beat = TRIP   },
	{.tone = B3,  .beat = TRIP   },
/*************************************/
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
/*C***********************************/
/*59**********************************/
	{.tone = Gs2, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Ds3, .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = Gs3, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G2,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = Gs2, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Ds3, .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = Gs3, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G2,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*63**********************************/
	{.tone = Gs2, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Ds3, .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	{.tone = Gs3, .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G2,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = D3,  .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = R,   .beat = WHOLE  },
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
/*D***********************************/
/*67**********************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Fs3, .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = D3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = B3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*71**********************************/
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = Fs3, .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = C4,  .beat = QUARTER},
	{.tone = F3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
/*************************************/
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = G3,  .beat = TRIP   },
	{.tone = A3   .beat = TRIP   },
	{.tone = B3,  .beat = TRIP   },
/*************************************/
	{.tone = C4,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = G3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = C3,  .beat = QUARTER},
	{.tone = R,   .beat = QUARTER},
	{.tone = R,   .beat = HALF   },
	
	{.tone = END}
}
