Note song[1024] = { 
	{.tone = E5,  .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = G5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*A************************************/
/*3************************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = E4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = B4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = As4, .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = G4,  .beat = TRIP   },
	{.tone = E5,  .beat = TRIP   },
	{.tone = G5,  .beat = TRIP   },
	{.tone = PASS},
	{.tone = A5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = G5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH   },
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
	{.tone = B4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*7************************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = E4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = B4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = As4, .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = G4,  .beat = TRIP   },
	{.tone = E5,  .beat = TRIP   },
	{.tone = G5,  .beat = TRIP   },
	{.tone = PASS},
	{.tone = A5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = G5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH },
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
	{.tone = B4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*B************************************/
/*11***********************************/
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G5,  .beat = EIGHTH},
	{.tone = Fs5, .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = Ds5, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = Gs4, .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G5,  .beat = EIGHTH},
	{.tone = Fs5, .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = Ds5, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = C6,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C6,  .beat = EIGHTH},
	{.tone = C6,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*15***********************************/
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G5,  .beat = EIGHTH},
	{.tone = Fs5, .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = Ds5, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = Gs4, .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = Ds5, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D5, .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/**************************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = R,   .beat = HALF  },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/*19***********************************/
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G5,  .beat = EIGHTH},
	{.tone = Fs5, .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = Ds5, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = Gs4, .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G5,  .beat = EIGHTH},
	{.tone = Fs5, .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = Ds5, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = C6,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C6,  .beat = EIGHTH},
	{.tone = C6,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*23***********************************/
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G5,  .beat = EIGHTH},
	{.tone = Fs5, .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = Ds5, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = Gs4, .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = Ds5, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = D5, .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/**************************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = R,   .beat = HALF  },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/*C************************************/
/*27***********************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/**************************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = HALF},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = R,   .beat = HALF},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/*31***********************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/**************************************/ 
	{.tone = E5,  .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = G5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*A************************************/
/*35***********************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = E4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = B4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = As4, .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = G4,  .beat = TRIP   },
	{.tone = E5,  .beat = TRIP   },
	{.tone = G5,  .beat = TRIP   },
	{.tone = PASS},
	{.tone = A5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = G5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
	{.tone = B4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*39***********************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = E4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = B4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = As4, .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = G4,  .beat = TRIP   },
	{.tone = E5,  .beat = TRIP   },
	{.tone = G5,  .beat = TRIP   },
	{.tone = PASS},
	{.tone = A5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = G5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH },
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
	{.tone = B4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*D************************************/
/*43***********************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
	{.tone = Gs4, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = A4,  .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/**************************************/
	{.tone = B4,  .beat = TRIP},
	{.tone = A5,  .beat = TRIP},
	{.tone = A5,  .beat = TRIP},
	{.tone = PASS},
	{.tone = A5,  .beat = TRIP},
	{.tone = G5,  .beat = TRIP},
	{.tone = F5,  .beat = TRIP},
	{.tone = PASS},
/**************************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/*47*********************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
	{.tone = Gs4, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = A4,  .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/**************************************/
	{.tone = B4,  .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = F5,  .beat = TRIP},
	{.tone = E5,  .beat = TRIP},
	{.tone = D5,  .beat = TRIP},
	{.tone = PASS},
/**************************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/*51***********************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
	{.tone = Gs4, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = A4,  .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/**************************************/
	{.tone = B4,  .beat = TRIP},
	{.tone = A5,  .beat = TRIP},
	{.tone = A5,  .beat = TRIP},
	{.tone = PASS},
	{.tone = A5,  .beat = TRIP},
	{.tone = G5,  .beat = TRIP},
	{.tone = F5,  .beat = TRIP},
	{.tone = PASS},
/**************************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/*55*********************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
	{.tone = Gs4, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = A4,  .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/**************************************/
	{.tone = B4,  .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = F5,  .beat = TRIP},
	{.tone = E5,  .beat = TRIP},
	{.tone = D5,  .beat = TRIP},
	{.tone = PASS},
/**************************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/*C************************************/
/*59***********************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/**************************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
/**************************************/
	{.tone = R,   .beat = WHOLE},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/*63***********************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = D5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/**************************************/ 
	{.tone = E5,  .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = E5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = G5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER   },
	{.tone = PASS},
/*D***********************************/
/*67*********************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
	{.tone = Gs4, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = A4,  .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/**************************************/
	{.tone = B4,  .beat = TRIP},
	{.tone = A5,  .beat = TRIP},
	{.tone = A5,  .beat = TRIP},
	{.tone = PASS},
	{.tone = A5,  .beat = TRIP},
	{.tone = G5,  .beat = TRIP},
	{.tone = F5,  .beat = TRIP},
	{.tone = PASS},
/**************************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/*71*********************************/
	{.tone = E5,  .beat = EIGHTH},
	{.tone = C5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = G4,  .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
	{.tone = Gs4, .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
/**************************************/
	{.tone = A4,  .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = A4,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},
/**************************************/
	{.tone = B4,  .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = F5,  .beat = EIGHTH},
	{.tone = F5,  .beat = TRIP},
	{.tone = E5,  .beat = TRIP},
	{.tone = D5,  .beat = TRIP},
	{.tone = PASS},
/**************************************/
	{.tone = C5,  .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = E3,  .beat = EIGHTH},
	{.tone = C3,  .beat = EIGHTH},
	{.tone = R,   .beat = EIGHTH},
	{.tone = R,   .beat = QUARTER},
	{.tone = PASS},

	{.tone = END}
};
