Note song[1024] = { 
	{.tone = D2,  .beat = HALFdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = E2,  .beat = HALFdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = F2,  .beat = HALFdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = E2,  .beat = HALFdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = D2,  .beat = HALFdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = E2,  .beat = HALFdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = F2,  .beat = HALFdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = E2,  .beat = HALFdot}, 
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = D2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
/***********************************/
	{.tone = E2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = G3,  .beat = HALF},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = F2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = A3,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = A3,  .beat = QUARTER},
	{.tone = PASS},
/***********************************/
	{.tone = E2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = G3,  .beat = HALF},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = As2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
/***********************************/
	{.tone = F2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = HALF},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = As2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
/***********************************/
	{.tone = A2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = E3,  .beat = HALF},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = D2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
/***********************************/
	{.tone = E2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = G3,  .beat = HALF},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = F2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = A3,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = A3,  .beat = QUARTER},
	{.tone = PASS},
/***********************************/
	{.tone = E2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = G3,  .beat = HALF},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = As2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
/***********************************/
	{.tone = A2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = E3,  .beat = HALF},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = D2,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
	{.tone = F3,  .beat = QUARTER},
	{.tone = PASS},
/***********************************/
	{.tone = D2,  .beat = HALFdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = E2,  .beat = HALFdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***********************************/
	{.tone = D2,  .beat = HALFdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},

	{.tone = END}
};
