Note song[1024] = { 
/***************************************/
	{.tone = R,  .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G3, .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G3, .beat = QUARTER   },
	{.tone = PASS},
/***************************************/
	{.tone = R,  .beat = EIGHTH    },
	{.tone = E3, .beat = EIGHTH    },
	{.tone = G3, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = R,  .beat = QUARTER   },
	{.tone = PASS},
	{.tone = A3, .beat = QUARTER   },
	{.tone = PASS},
	{.tone = A3, .beat = QUARTER   },
	{.tone = PASS},
/***************************************/
	{.tone = R,  .beat = EIGHTH    },
	{.tone = E3, .beat = EIGHTH    },
	{.tone = G3, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = R,  .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G3, .beat = QUARTER   },
	{.tone = PASS},
	{.tone = G3, .beat = QUARTER   },
	{.tone = PASS},
/***************************************/
	{.tone = R,  .beat = EIGHTH    },
	{.tone = E3, .beat = EIGHTH    },
	{.tone = G3, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = R,  .beat = QUARTER   },
	{.tone = PASS},
	{.tone = A3, .beat = QUARTER   },
	{.tone = PASS},
	{.tone = A3, .beat = QUARTER   },
	{.tone = PASS},
/***************************************/
	{.tone = R,  .beat = EIGHTH    },
	{.tone = E3, .beat = EIGHTH    },
	{.tone = G3, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = D4, .beat = EIGHTH    },
	{.tone = F4, .beat = EIGHTH    },
	{.tone = D5, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = D4, .beat = EIGHTH    },
	{.tone = F4, .beat = EIGHTH    },
	{.tone = D5, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = E5, .beat = QUARTERdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = F5, .beat = EIGHTH    },
	{.tone = E5, .beat = EIGHTH    },
	{.tone = F5, .beat = EIGHTH    },
/***************************************/
	{.tone = E5, .beat = EIGHTH    },
	{.tone = C5, .beat = EIGHTH    },
	{.tone = A4, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = A4, .beat = QUARTER   },
	{.tone = PASS},
	{.tone = D4, .beat = QUARTER   },
	{.tone = PASS},
	{.tone = F4, .beat = EIGHTH    },
	{.tone = G4, .beat = EIGHTH    },
/***************************************/
	{.tone = A4, .beat = HALFdot   },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = A4, .beat = QUARTER   },
	{.tone = PASS},
	{.tone = D4, .beat = QUARTER   },
	{.tone = PASS},
	{.tone = F4, .beat = EIGHTH    },
	{.tone = G4, .beat = EIGHTH    },
/***************************************/
	{.tone = E4, .beat = HALFdot   },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = D4, .beat = EIGHTH    },
	{.tone = F4, .beat = EIGHTH    },
	{.tone = D5, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = D4, .beat = EIGHTH    },
	{.tone = F4, .beat = EIGHTH    },
	{.tone = D5, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = E5, .beat = QUARTERdot},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = F5, .beat = EIGHTH    },
	{.tone = E5, .beat = EIGHTH    },
	{.tone = F5, .beat = EIGHTH    },
/***************************************/
	{.tone = E5, .beat = EIGHTH    },
	{.tone = C5, .beat = EIGHTH    },
	{.tone = A4, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = A4, .beat = QUARTER   },
	{.tone = PASS},
	{.tone = D4, .beat = QUARTER   },
	{.tone = PASS},
	{.tone = F4, .beat = EIGHTH    },
	{.tone = G4, .beat = EIGHTH    },
/***************************************/
	{.tone = A4, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = A4, .beat = QUARTER   },
	{.tone = PASS},
/***************************************/
	{.tone = D4, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
	{.tone = R,  .beat = QUARTER    },
	{.tone = PASS},
/***************************************/
	{.tone = R,  .beat = EIGHTH    },
	{.tone = E3, .beat = EIGHTH    },
	{.tone = G3, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},
/***************************************/
	{.tone = R,  .beat = QUARTER   },
	{.tone = PASS},
	{.tone = A3, .beat = QUARTER   },
	{.tone = PASS},
	{.tone = A3, .beat = QUARTER   },
	{.tone = PASS},
/***************************************/
	{.tone = R,  .beat = EIGHTH    },
	{.tone = E3, .beat = EIGHTH    },
	{.tone = G3, .beat = HALF      },
	{.tone = PASS},
	{.tone = PASS},
	{.tone = PASS},

	{.tone = END}
};
